### PR TITLE
feat(289): Labeled markers

### PR DESCRIPTION
**Pull request by tomorrowevening**
For feature https://github.com/theatre-js/theatre/issues/289

### CODE REVIEW

**Comment by tomorrowevening** [comment]
Helpful with animation organization + sectioning off the timeline for specific purposes.
Could be helpful in the future to export markers in `state.json` too so there's clarity between multiple devs/animators.
If markers become part of the actual timeline, then functionality for `playMarker("show")` make it easy and clearer, especially if animation durations keep getting updated.
Screen Shot 2022-12-21 at 5 32 18 PM

**Comment by AriaMinaei** [comment]
This is great! We'll tweak the UX a bit and then merge this in. (I'm thinking we'd hide the label and show it on hover, similar to how the sequence length indicator works).

**Comment by tomorrowevening** [comment]
Sounds good to me! Thanks!

**Comment by AriaMinaei** [comment]
Thanks @tomorrowevening!

**Pull request merged**
