### PR TITLE
New feature: Keyframe "hold" as a new easing type

### PR DESCRIPTION
**Pull request by tomorrowevening**
To fix issue [291](https://github.com/theatre-js/theatre/issues/291) @AriaMinaei @AndrewPrifer

### CODE REVIEW

**Comment by tomorrowevening** [comment]
A nondestructive way of applying hold keyframes without erasing prior curve history

https://user-images.githubusercontent.com/626143/208997943-ea38405e-64ae-429c-a7f8-4730788aee43.mp4

**Comment by AriaMinaei** [comment]
This PR should come with epic bg music! Seriously amazing work @tomorrowevening!

**Comment by AriaMinaei** [comment]
@tomorrowevening the feature works very well!

Can you write a few words on the design decisions you made?

Separately, I was thinking of making `hold` be one of the options in the `CurveEditorPopover`. 

Screenshot 2022-12-23 at 21 14 50

My reasons are:
1. Would avoid adding an extra "concept" (although behind the scenes, it would keep the `type: 'hold'` annotation to make `hold`ing a keyframe non-destructive to the existing curve.
2. Would be faster to set different keyframes to "hold" by just clicking on them and hitting "h" and hitting "enter" (as it would re-use the fuzzy-matcher of the `CurveEditorPopover`.

What do you think of this idea?

**Comment by tomorrowevening** [comment]
Sounds good to me 👍

**Comment by tomorrowevening** [comment]
I'll need help with these additional requests.
Essentially, we'd have to also update the keyframe type [here](https://github.com/theatre-js/theatre/blob/fcd3ab7ec50d8236285a61ba44f4bdf966453bb5/theatre/studio/src/panels/SequenceEditorPanel/DopeSheet/Right/BasicKeyframedTrack/KeyframeEditor/CurveEditorPopover/CurveEditorPopover.tsx#L290), as well as update the SVG for conditional rendering [here](https://github.com/theatre-js/theatre/blob/main/theatre/studio/src/panels/SequenceEditorPanel/DopeSheet/Right/BasicKeyframedTrack/KeyframeEditor/CurveEditorPopover/SVGCurveSegment.tsx) and [here](https://github.com/theatre-js/theatre/blob/main/theatre/studio/src/panels/SequenceEditorPanel/DopeSheet/Right/BasicKeyframedTrack/KeyframeEditor/CurveEditorPopover/CurveSegmentEditor.tsx) to render something like:
```
return (
  <svg
    height="100%"
    width="100%"
    viewBox={SVG_VIEWBOX_ATTR}
    fill="none"
    xmlns="http://www.w3.org/2000/svg"
  >
    {/* Control lines */}
    <line
      x1="0"
      y1="1"
      x2={1}
      y2={1}
      stroke={curveColor}
      strokeWidth="0.08"
    />
    <line
      x1="1"
      y1="0"
      x2={1}
      y2={1}
      stroke={curveColor}
      strokeWidth="0.08"
    />
    <circle cx={0} cy={1} r={SVG_CIRCLE_RADIUS} fill={curveColor} />
    <circle cx={1} cy={0} r={SVG_CIRCLE_RADIUS} fill={curveColor} />
  </svg>
)
```

**Comment by tomorrowevening** [comment]
All set 👍

**Comment by AriaMinaei** [comment]
So excited to finally have this functionality! Thank you @tomorrowevening 🙌

**Pull request merged**
